### ISSUE TITLE
Issue with response body transformation

### ISSUE THREAD

**Issue by Franciscuo** [nolleh/serialize-interceptor#1]
I am encountering an issue while sending a camelCase formatted object in the response body using Nestjs for my backend service.

When I send the following object in camelCase format:

```
{
  id: 4,
  customerId: 4,
  birthdate: null,
  availablePoints: 'test_snake_case',
  redeemedPoints: 'testCamelCase',
  createdAt: new Date('2023-05-31T11:43:31.069Z'),
  updatedAt: '2023-05-31T11:43:31.069Z'
}
```

The object is being transformed automatically and returned as:

```
{
  "id": 4,
  "customer_id": 4,
  "birthdate": null,
  "available_points": "test_snake_case",
  "redeemed_points": "testCamelCase",
  "created_at": {},
  "updated_at": "2023-05-31T11:43:31.069Z"
}
```

In the transformed object, the property createdAt is replaced with an empty object {} instead of maintaining its original value.

**Comment by nolleh** [comment]
oh, thx for report and PR.
unfortunately I am now in vacation, so checking PR will be delayed..It will be at 6.5~6.6,(KST)

I'm gonna imform you after that!
sincery, thanx.

**Comment by nolleh** [comment]
your request https://github.com/nolleh/serialize-interceptor/pull/2
was merged and released as new version :)
